CREATE DATABASE last_lab;

--Table
CREATE TABLE accounts (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    balance DEC(15,2) NOT NULL,
    PRIMARY KEY(id)
);


INSERT INTO accounts(name,balance)
VALUES('Bob',10000);
SELECT * FROM accounts;
BEGIN TRANSACTION;
INSERT INTO accounts(name,balance)
VALUES('Alice',10000);
SELECT * FROM accounts;
COMMIT TRANSACTION;



-- start a transaction
BEGIN;

-- deduct 1000 from account 1
UPDATE accounts
SET balance = balance - 1000
WHERE id = 1;

-- add 1000 to account 2
UPDATE accounts
SET balance = balance + 1000
WHERE id = 2;

-- select the data from accounts
SELECT id, name, balance
FROM accounts;

-- commit the transaction
COMMIT;


INSERT INTO accounts(name, balance)
VALUES('Jack',0);


-- begin the transaction
BEGIN;

-- deduct the amount from the account 1
UPDATE accounts
SET balance = balance - 1500
WHERE id = 1;

-- add the amount from the account 3 (instead of 2)
UPDATE accounts
SET balance = balance + 1500
WHERE id = 3;

-- roll back the transaction
ROLLBACK;

-- select the data from accounts
SELECT id, name, balance
FROM accounts;

